spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dodami-db.cvynqgy7fprz.ap-northeast-2.rds.amazonaws.com:5432/dodami
    username: dodami
    password: dodamipostgres
    platform: POSTGRESQL
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: quest
    port: 5672
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1

JWT:
  ISSUER: DODAMI
  SECRET: sdjaf3i@#$%13469ktmrEOGJERAfier*&

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: dodami-bucket
      bucket_url: https://s3.ap-northeast-2.amazonaws.com/dodami-bucket
    region:
      auto: false
      static: ap-northeast-2

myqueue: rabbitmq
